# Generated by Django 4.0.4 on 2023-01-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('hobbies', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=25)),
            ],
        ),
    ]
